### ISSUE TITLE
cvs2git malforms binary (-kb) files

### ISSUE THREAD

**Issue by rlaPHOENiX** [mhagger/cvs2svn#12]
It's doing the thing where anywhere theres text e.g. `$Name$` it will convert that to something like `$Name:   $`. This will make the binary file unusable/report corrupted when using it for compiling e.t.c.

Is there any workaround?

**Comment by mhagger** [comment]
Sometimes this is caused by not marking the file as binary in CVS, and CVS is doing the expansion. Sometimes it is caused by using CVSNT's binary file feature, which differs from that of standard CVS. I no longer remember all of the details, but you can refer to https://github.com/mhagger/cvs2svn/blob/master/doc/text-transformations.txt for general background information. Also search for strings like `--keywords-off` and `--auto-props` in the `www` directory for more info.
