### ISSUE TITLE
CVS2GIT ERROR

### ISSUE THREAD

**Issue by ksiraj786** [mhagger/cvs2svn#3]
Hi I am a newbie to GIT. I have a CVS repository on m local computer and i am trying to migrate it to GIT.

I am using the following command.

C:\Users\testuser\Downloads\CVS2SVN\dist\cvs2svn-2.4.0> python cvs2git 
   --blobfile=C:\Demos\cvsmigration\git-shoping-blob.dat
   --dumpfile=C:\Demos\cvsmigration\git-shoping-dump.dat
   --username=cvs2git
   C:\Demos\cvsrepo

Above command exit with the following error.

Filtering out excluded symbols and summarizing items...
ERROR: The command 'cvs -Q -f -d :local:C:\Demos\cvsrepo co -r1.1 -p -kb CVSRO
OT/checkoutlist' failed with exit status=0
and the following output:
cvs checkout: cwd=C:\Users\testuser\Downloads\CVS2SVN\dist\cvs2svn-2.4.0 ,curren
t=C:\Users\testuser\Downloads\CVS2SVN\dist\cvs2svn-2.4.0

Any help please ..!!

**Comment by anshul14** [comment]
Hi mhagger

I know this is a very old post and the chances of a reply are bleak but I would take my chances. 

I am running into an issue with cvs2git migration. Following are the steps that I am following:

I have a Local snapshot of the repository that has CVSROOT and the projects
Then I ran the following command to get the .dat file generated but the files are not generating and I am getting the following error at the Pass 4
Command 
python cvs2git.bat --blobfile=C:\files\git-blob.dat --dumpfile=C:\files\git-dump.dat --username= --encoding=utf8

ERROR: Filtering out excluded symbols and summarizing items... ERROR: The command 'cvs -Q -R -f -d :local:C:\ABC\Work\Migration\FH\Fuzon co -r1.1 -p -kb CVSROOT/checkoutlist' failed with exit status=1 and the following output: cvs checkout: connect to 127.0.0.1(127.0.0.1:2402):2402 failed: No connection could be made because the target machine actively refused it. cvs [checkout aborted]: Couldn't connect to lock server

I tried to connect to the actual cvs server also and then run the command but it still failed. I am using Windows 7 box.

Anyway I can overcome this issue.

**Comment by mhagger** [comment]
@anshul14: please use the mailing list for cvs2svn/cvs2git questions. This GitHub repository is only a mirror that I use for my own purposes.

**Comment by anshul14** [comment]
My bad Michael. Apologies for that.

I have sent the email to
dev@cvs2svn.tigris.org as wellwith my issue.

Thanks again
Anshul

**Comment by sscheiner** [comment]
Just wanted to chime in here to share my solution to this problem in a windows dev environment:

I adapted an approach mentioned [here](http://tigris-scm.10930.n7.nabble.com/cvs2git-problem-td98521.html) to wrap cvs.exe with a batch file that redirects cvs output to null. I created a windows executable using [this C# program](https://stackoverflow.com/a/54706445) and the .NET compiler to call this batch file when CVS is called. This allowed me to run cvs2git without any issues.
